"""
services/ai_router.py — OpenAI-powered intent router for OfficePilot AI.

Flow:
  1. User message + session history → OpenAI (gpt-4o-mini)
  2. Model either replies in natural language OR calls one of the defined tools
  3. Caller receives a structured action dict → dispatched to existing backend handlers

Tool names map 1-to-1 to existing services; NO data is generated by the LLM.
"""

import json
import logging
from openai import OpenAI

logger = logging.getLogger(__name__)

# ── System prompt ─────────────────────────────────────────────────────────────

_SYSTEM = (
    "You are an office automation assistant for Dar Al Salam Engineering Turning Works, "
    "an engineering workshop in Sharjah, UAE. "
    "Your job is to detect user intent and call the correct tool.\n\n"
    "You help with: quotation generation, customer ledger / outstanding balances, "
    "invoice entry, payment recording, account statement PDF, and official document delivery.\n\n"
    "You understand English, Hindi, Urdu, and Hinglish. Common terms:\n"
    "  bhejo / send karo = send   |  kitna hai = how much   |  banana hai = create\n"
    "  outstanding = unpaid balance   |  ka/ki/ke = of/for\n\n"
    "Company aliases:\n"
    "  gulf → GULF EXTRUSION COMPANY LLC\n"
    "  islami → AL ISLAMI FOODS\n"
    "  quant → QUANTICO\n"
    "  globol / global → GLOBAL OFFSHORE SERVICES\n"
    "  tayseer → TAYSEER ARAR\n"
    "  canadian → CANADIAN CARTON\n\n"
    "Rules:\n"
    "  1. Call the correct tool as soon as you have enough information.\n"
    "  2. If information is missing, ask ONE short question.\n"
    "  3. Never invent quotation numbers, balances, or file paths — all real data comes from tools.\n"
    "  4. Respond briefly and professionally.\n"
    "  5. For greetings or help requests, describe your capabilities warmly."
)

# ── Tool definitions (OpenAI function-calling format) ─────────────────────────

_TOOLS = [
    {
        "type": "function",
        "function": {
            "name": "generate_quotation",
            "description": (
                "Create a professional quotation (Excel + PDF) for a client. "
                "Call when the user wants to make/create a quotation and you have the company name "
                "and at least one item."
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "company": {
                        "type": "string",
                        "description": "Client company name or alias (e.g. 'gulf', 'islami')"
                    },
                    "items": {
                        "type": "array",
                        "description": "List of line items to quote",
                        "items": {
                            "type": "object",
                            "properties": {
                                "description": {"type": "string"},
                                "qty":         {"type": "number"},
                                "rate":        {"type": "number"}
                            },
                            "required": ["description", "qty", "rate"]
                        }
                    }
                },
                "required": ["company", "items"]
            }
        }
    },
    {
        "type": "function",
        "function": {
            "name": "get_ledger",
            "description": (
                "Get the outstanding balance and recent ledger entries for a company. "
                "Use for 'balance', 'outstanding', 'kitna baki hai', 'ledger' queries."
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "company": {"type": "string", "description": "Company name or alias"}
                },
                "required": ["company"]
            }
        }
    },
    {
        "type": "function",
        "function": {
            "name": "add_ledger_entry",
            "description": "Add a new debit (invoice) entry to a company's ledger.",
            "parameters": {
                "type": "object",
                "properties": {
                    "company": {"type": "string"},
                    "invoice": {"type": "string", "description": "Invoice number"},
                    "amount":  {"type": "number", "description": "Invoice amount in AED"},
                    "lpo":     {"type": "string", "description": "LPO number if mentioned, optional"}
                },
                "required": ["company", "invoice", "amount"]
            }
        }
    },
    {
        "type": "function",
        "function": {
            "name": "record_payment",
            "description": (
                "Record a payment (credit) received from a client against an invoice. "
                "Use for 'payment received', 'payment aaya', 'payment mil gaya'."
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "company": {"type": "string"},
                    "invoice": {"type": "string"},
                    "amount":  {"type": "number"},
                    "date":    {"type": "string", "description": "DD-MM-YYYY, optional"}
                },
                "required": ["company", "invoice", "amount"]
            }
        }
    },
    {
        "type": "function",
        "function": {
            "name": "generate_statement",
            "description": (
                "Generate a professional A4 account statement PDF for a company for a specific month. "
                "Use for 'statement', 'account statement chahiye', 'send statement'."
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "company": {"type": "string"},
                    "month":   {"type": "integer", "description": "Month as number 1-12"},
                    "year":    {"type": "integer", "description": "4-digit year, e.g. 2026"},
                    "mode":    {
                        "type": "string",
                        "enum": ["full", "unpaid"],
                        "description": "full=all entries (default), unpaid=only outstanding"
                    }
                },
                "required": ["company", "month", "year"]
            }
        }
    },
    {
        "type": "function",
        "function": {
            "name": "fetch_document",
            "description": (
                "Fetch and send an official document file (trade license, shed contract, "
                "municipality certificate, establishment card, etc.). "
                "Use for 'send DOCUMENT', 'bhejo DOCUMENT', 'doc chahiye'."
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "query": {
                        "type": "string",
                        "description": "Document name or partial name to search for"
                    }
                },
                "required": ["query"]
            }
        }
    },
]

# ── Client singleton ──────────────────────────────────────────────────────────

_client: "OpenAI | None" = None


def _get_client() -> "OpenAI | None":
    from app.config import settings
    key = getattr(settings, "OPENAI_API_KEY", "")
    if not key:
        return None
    global _client
    if _client is None:
        _client = OpenAI(api_key=key)
    return _client


# ── Tool name → action type map ───────────────────────────────────────────────

_TOOL_TYPE = {
    "generate_quotation": "quotation",
    "get_ledger":         "ledger",
    "add_ledger_entry":   "add_entry",
    "record_payment":     "payment",
    "generate_statement": "statement",
    "fetch_document":     "document",
}


# ── Main entry point ──────────────────────────────────────────────────────────

def route(user_message: str, history: list[dict], session: "dict | None" = None) -> dict:
    """
    Route a user message through gpt-4o-mini and return a structured action dict.

    Return shapes:
      {"type": "chat",      "reply": str}
      {"type": "quotation", "company": str, "items": list}
      {"type": "ledger",    "company": str}
      {"type": "add_entry", "company": str, "invoice": str, "amount": float, "lpo": str}
      {"type": "payment",   "company": str, "invoice": str, "amount": float, "date": str}
      {"type": "statement", "company": str, "month": int, "year": int, "mode": str}
      {"type": "document",  "query": str}
      {"type": "error",     "reply": str}
    """
    client = _get_client()
    if client is None:
        return {
            "type": "error",
            "reply": (
                "⚠️ AI assistant not configured.\n"
                "Add <code>OPENAI_API_KEY=your_key</code> to your <code>.env</code> file and restart."
            )
        }

    # Inject active-company context into system prompt
    system = _SYSTEM
    if session and session.get("active_company"):
        system += f"\n\nActive company in this session: {session['active_company']}"

    messages = (
        [{"role": "system", "content": system}]
        + list(history)
        + [{"role": "user", "content": user_message}]
    )

    try:
        response = client.chat.completions.create(
            model="gpt-4o-mini",
            max_tokens=512,
            tools=_TOOLS,
            tool_choice="auto",
            messages=messages,
        )
    except Exception as exc:
        logger.exception("OpenAI API error in ai_router.route")
        return {"type": "error", "reply": f"⚠️ AI error: {exc}"}

    msg = response.choices[0].message

    # ── Tool call → structured action ─────────────────────────────────────────
    if msg.tool_calls:
        call = msg.tool_calls[0]
        name = call.function.name
        try:
            args = json.loads(call.function.arguments)
        except (json.JSONDecodeError, ValueError):
            args = {}

        logger.info("AI tool call: %s  params=%s", name, args)

        action_type = _TOOL_TYPE.get(name)
        if action_type:
            result = {"type": action_type, **args}
            # Ensure statement has a default mode
            if action_type == "statement":
                result.setdefault("mode", "full")
            return result

    # ── Text reply ────────────────────────────────────────────────────────────
    reply = (msg.content or "").strip()
    if not reply:
        reply = "I'm not sure how to help with that. Try: <b>help</b>"
    return {"type": "chat", "reply": reply}
