"""
services/ai_router.py — Claude-powered intent router for OfficePilot AI.

Flow:
  1. User message + session history → Claude (claude-haiku-4-5-20251001)
  2. Claude either replies in natural language OR calls one of the defined tools
  3. Caller receives a structured action dict → dispatched to existing backend handlers

Tool names map 1-to-1 to existing services; NO data is generated by the LLM.
"""

import logging
from anthropic import Anthropic

logger = logging.getLogger(__name__)

# ── System prompt ─────────────────────────────────────────────────────────────

_SYSTEM = """You are OfficePilot AI, a professional business assistant for Dar Al Salam Engineering \
Turning Works — an engineering workshop in Sharjah, UAE.

You help with:
  • Quotation generation (Excel + PDF)
  • Customer ledger / outstanding balances
  • Invoice entry and payment recording
  • Account statement PDF generation
  • Official document delivery

You understand English, Hindi, Urdu, and Hinglish. Common terms users may use:
  bhejo / send karo     = send / deliver
  kitna hai / kya hai   = how much / what is
  banana hai / banao    = create / make
  outstanding           = unpaid balance
  ka / ki / ke          = of / for (e.g. "gulf ka balance" = gulf's balance)
  statement chahiye     = I need a statement
  quotation banana hai  = I need a quotation

Company aliases (resolve automatically):
  gulf / gulf extrusion  → GULF EXTRUSION COMPANY LLC
  islami                 → AL ISLAMI FOODS
  quant / quantico       → QUANTICO
  globol / global        → GLOBAL OFFSHORE SERVICES
  tayseer                → TAYSEER ARAR
  canadian               → CANADIAN CARTON

Rules:
  1. When you have enough information, call the appropriate tool immediately.
  2. When you need more information, ask ONE clear question.
  3. NEVER invent file paths, quotation numbers, amounts, or balances.
  4. All real data comes from backend tools only — never hallucinate business data.
  5. Respond briefly and professionally. No long explanations unless asked.
  6. For greetings or general questions, respond warmly and mention your capabilities.

Capabilities summary for help responses:
  • Quotations: "make quotation for COMPANY, item 1: description qty N price N each"
  • Ledger: "balance for COMPANY" or "outstanding COMPANY"
  • Payments: "payment received from COMPANY invoice N amount N"
  • Statements: "statement for COMPANY MONTH YEAR"
  • Documents: "send DOCUMENT NAME" (trade license, shed contract, municipality, etc.)
"""

# ── Tool definitions ──────────────────────────────────────────────────────────

_TOOLS = [
    {
        "name": "generate_quotation",
        "description": (
            "Create a professional quotation (Excel + PDF) for a client. "
            "Call this when the user wants to make/create a quotation and you have the company name and at least one item."
        ),
        "input_schema": {
            "type": "object",
            "properties": {
                "company": {
                    "type": "string",
                    "description": "Client company name or alias (e.g. 'gulf', 'islami')"
                },
                "items": {
                    "type": "array",
                    "description": "List of line items to quote",
                    "items": {
                        "type": "object",
                        "properties": {
                            "description": {"type": "string"},
                            "qty":         {"type": "number"},
                            "rate":        {"type": "number"}
                        },
                        "required": ["description", "qty", "rate"]
                    }
                }
            },
            "required": ["company", "items"]
        },
    },
    {
        "name": "get_ledger",
        "description": (
            "Get the outstanding balance and recent ledger entries for a company. "
            "Use this for 'balance', 'outstanding', 'kitna baki hai', 'ledger' queries."
        ),
        "input_schema": {
            "type": "object",
            "properties": {
                "company": {"type": "string", "description": "Company name or alias"}
            },
            "required": ["company"]
        },
    },
    {
        "name": "add_ledger_entry",
        "description": "Add a new debit (invoice) entry to a company's ledger.",
        "input_schema": {
            "type": "object",
            "properties": {
                "company": {"type": "string"},
                "invoice": {"type": "string", "description": "Invoice number"},
                "amount":  {"type": "number", "description": "Invoice amount in AED"},
                "lpo":     {"type": "string", "description": "LPO number if mentioned, optional"}
            },
            "required": ["company", "invoice", "amount"]
        },
    },
    {
        "name": "record_payment",
        "description": (
            "Record a payment (credit) received from a client against an invoice. "
            "Use for 'payment received', 'payment aaya', 'payment mil gaya'."
        ),
        "input_schema": {
            "type": "object",
            "properties": {
                "company": {"type": "string"},
                "invoice": {"type": "string"},
                "amount":  {"type": "number"},
                "date":    {"type": "string", "description": "DD-MM-YYYY, optional — leave blank for today"}
            },
            "required": ["company", "invoice", "amount"]
        },
    },
    {
        "name": "generate_statement",
        "description": (
            "Generate a professional A4 account statement PDF for a company for a specific month. "
            "Use for 'statement', 'account statement chahiye', 'send statement'."
        ),
        "input_schema": {
            "type": "object",
            "properties": {
                "company": {"type": "string"},
                "month":   {"type": "integer", "description": "Month as number 1–12"},
                "year":    {"type": "integer", "description": "4-digit year, e.g. 2026"},
                "mode":    {
                    "type": "string",
                    "enum": ["full", "unpaid"],
                    "description": "full=all entries (default), unpaid=only outstanding invoices"
                }
            },
            "required": ["company", "month", "year"]
        },
    },
    {
        "name": "fetch_document",
        "description": (
            "Fetch and send an official document file (trade license, shed contract, "
            "municipality certificate, establishment card, etc.). "
            "Use for 'send DOCUMENT', 'bhejo DOCUMENT', 'doc chahiye'."
        ),
        "input_schema": {
            "type": "object",
            "properties": {
                "query": {
                    "type": "string",
                    "description": "Document name or partial name to search for"
                }
            },
            "required": ["query"]
        },
    },
]

# ── Month names (for statement command reconstruction) ────────────────────────

_MONTH_NAMES = [
    "", "january", "february", "march", "april", "may", "june",
    "july", "august", "september", "october", "november", "december",
]

# ── Client singleton ──────────────────────────────────────────────────────────

_client: "Anthropic | None" = None


def _get_client() -> "Anthropic | None":
    from app.config import settings
    key = getattr(settings, "ANTHROPIC_API_KEY", "")
    if not key:
        return None
    global _client
    if _client is None:
        _client = Anthropic(api_key=key)
    return _client


# ── Main entry point ──────────────────────────────────────────────────────────

def route(user_message: str, history: list[dict], session: "dict | None" = None) -> dict:
    """
    Route a user message through Claude and return a structured action dict.

    Return shapes:
      {"type": "chat",      "reply": str}
      {"type": "quotation", "company": str, "items": list}
      {"type": "ledger",    "company": str}
      {"type": "add_entry", "company": str, "invoice": str, "amount": float, "lpo": str}
      {"type": "payment",   "company": str, "invoice": str, "amount": float, "date": str}
      {"type": "statement", "company": str, "month": int, "year": int, "mode": str}
      {"type": "document",  "query": str}
      {"type": "error",     "reply": str}
    """
    client = _get_client()
    if client is None:
        return {
            "type": "error",
            "reply": (
                "⚠️ AI assistant not configured.\n"
                "Add <code>ANTHROPIC_API_KEY=your_key</code> to your <code>.env</code> file and restart."
            )
        }

    # Inject active-company context into system prompt
    system = _SYSTEM
    if session and session.get("active_company"):
        system += f"\n\nActive company in this session: {session['active_company']}"

    messages = list(history) + [{"role": "user", "content": user_message}]

    try:
        response = client.messages.create(
            model="claude-haiku-4-5-20251001",
            max_tokens=512,
            system=system,
            tools=_TOOLS,
            messages=messages,
        )
    except Exception as exc:
        logger.exception("Claude API error in ai_router.route")
        return {"type": "error", "reply": f"⚠️ AI error: {exc}"}

    # ── Tool call → structured action ─────────────────────────────────────────
    for block in response.content:
        if block.type == "tool_use":
            name = block.name
            inp  = block.input or {}
            logger.info("AI tool call: %s  params=%s", name, inp)

            if name == "generate_quotation":
                return {"type": "quotation", **inp}
            if name == "get_ledger":
                return {"type": "ledger", **inp}
            if name == "add_ledger_entry":
                return {"type": "add_entry", **inp}
            if name == "record_payment":
                return {"type": "payment", **inp}
            if name == "generate_statement":
                return {"type": "statement", "mode": "full", **inp}
            if name == "fetch_document":
                return {"type": "document", **inp}

    # ── Text reply ────────────────────────────────────────────────────────────
    text_blocks = [b.text for b in response.content if hasattr(b, "text")]
    reply = "\n".join(text_blocks).strip()
    if not reply:
        reply = "I'm not sure how to help with that. Try: <b>help</b>"
    return {"type": "chat", "reply": reply}
